### ISSUE TITLE
After running the tool, win terminal sometimes has an incorrect tile size

### ISSUE THREAD

**Issue by DreamMaoMao** [ptazithos/glazewm-extra#12]
![image](https://github.com/user-attachments/assets/00e5b8a5-b28a-483a-9eee-0e9ed7e79990)

After running the tool, win terminal sometimes has an incorrect tile size, as shown in the figure, win terminal does not automatically tile the screen, which does not appear when the tool is not running

**Comment by ptazithos** [comment]
May I know your glazewm-extra config?

**Comment by DreamMaoMao** [comment]
> May I know your glazewm-extra config?

```toml
[[window_rules]]
command = "set title false"
match_process_name = ".*"

[[window_rules]]
command = "set rounded true"
match_process_name = ".*"

[[focused_window_rules]]
command = "set translucent 255"
match_process_name = ".*"

[[unfocused_window_rules]]
command = "set translucent 220"
match_process_name = ".*"

```
