### ISSUE TITLE
[Feature] Exclude windows from transparency and title bar removal

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [ptazithos/glazewm-extra#4]
This has merely aesthetic usecases. It would be good to have a way to exclude some windows from the transparency feature, since, for example, a terminal may have a transparent background and I might not want it to look more transparent.

**Comment by ptazithos** [comment]
Done. See the new config:
```toml
# Rules applied for every windows once the window creates.
[[window_rules]]
command = "set title false"
match_process_name = ".*"

# Rules applied for the focused window when focus changes.
[[focused_window_rules]]
command = "set translucent 255"
match_process_name = ".*"

# Rule applied for unfocused windows when focus change.
[[unfocused_window_rules]]
command = "set translucent 220"
match_process_name = ".*"
```
Except `match_process_name `, `match_class_name` and `match_title` are also available.
